fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev:  21.5b1
    hooks:
      - id:               black
        language_version: python3.9
  - repo: local
    hooks:
      - id:             pytest-check
        name:           pytest-check
        entry:          pytest
        language:       system
        pass_filenames: false
        always_run:     true