dist:     xenial
language: python
python:
  - '3.6'
#  - '3.7'
#  - '3.8'
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - pytest #--cov=warg
  - coveralls
  #- scripts/build_and_upload_package.sh

